### PR TITLE
Version 1.1.0

### PR DESCRIPTION
**Pull request by MathisRosenhauer**

### CODE REVIEW

**Comment by shahramn** [comment]
A thousand thanks! This is VERY much appreciated

**Comment by shahramn** [comment]
Will this be added to the "Releases" page?
https://github.com/MathisRosenhauer/libaec/releases

**Comment by shahramn** [comment]
I hope this new version will turn up in **Homebrew** for macOS

**Comment by MathisRosenhauer** [comment]
@joobog is investigating a potential last minute bug. Until then I haven't tagged the release so the distros are not making their packages. It could be that we skip this release and go with 1.1.1 instead.

**Pull request merged**
